import { FC } from 'react';

export const TermsView: FC<{ onBack?: () => void }> = ({ onBack }) => {
  return (
    <div className="max-w-2xl mx-auto px-4 py-8 space-y-6 pb-28">
      {onBack && (
        <button onClick={onBack} className="text-sm text-indigo-400 hover:text-indigo-300 transition-colors mb-2">
          ← Back
        </button>
      )}
      <h1 className="text-2xl font-bold text-zinc-100">Terms of Service</h1>
      <p className="text-xs text-zinc-500">Last updated: March 2025</p>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-zinc-200">1. Acceptance of Terms</h2>
        <p className="text-sm text-zinc-400 leading-relaxed">
          By accessing or using Solia ("the Platform"), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the Platform. Solia is an AI-powered content creation and monetization platform built on the Solana blockchain.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-zinc-200">2. Platform Description</h2>
        <p className="text-sm text-zinc-400 leading-relaxed">
          Solia enables users to generate images using artificial intelligence, publish them to a public feed, and monetize their creations through on-chain transactions on the Solana blockchain. All purchases, tips, and transfers are executed using SPL tokens (SKR) on the Solana network.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-zinc-200">3. Non-Custodial Wallet</h2>
        <p className="text-sm text-zinc-400 leading-relaxed">
          Solia is a <strong className="text-zinc-300">non-custodial platform</strong>. We do not store, manage, or have access to your private keys, seed phrases, or wallet credentials. You are solely responsible for the security of your wallet and any transactions you authorize. Solia connects to third-party wallet providers (such as Phantom, Solflare, and others) via the Wallet Standard protocol. We have no control over these wallet applications.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-zinc-200">4. User Responsibilities</h2>
        <p className="text-sm text-zinc-400 leading-relaxed">
          You are fully responsible for:
        </p>
        <ul className="list-disc list-inside text-sm text-zinc-400 space-y-1 ml-2">
          <li>Safeguarding your wallet private keys and recovery phrases.</li>
          <li>All transactions you approve through your wallet.</li>
          <li>All content you generate, publish, or share on the Platform.</li>
          <li>Ensuring your use of the Platform complies with applicable laws in your jurisdiction.</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-zinc-200">5. AI-Generated Content</h2>
        <p className="text-sm text-zinc-400 leading-relaxed">
          Content on Solia is generated by artificial intelligence based on text prompts provided by users. You acknowledge that:
        </p>
        <ul className="list-disc list-inside text-sm text-zinc-400 space-y-1 ml-2">
          <li>AI-generated images may not always be accurate, appropriate, or free from bias.</li>
          <li>You are solely responsible for the prompts you submit and the resulting content.</li>
          <li>You must not use the Platform to generate content that is illegal, harmful, defamatory, or infringes on third-party rights.</li>
          <li>Solia reserves the right to remove content that violates these terms or applicable law.</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-zinc-200">6. Blockchain Transactions</h2>
        <p className="text-sm text-zinc-400 leading-relaxed">
          All financial transactions on Solia occur on the Solana blockchain and are <strong className="text-zinc-300">irreversible</strong>. Once a transaction is confirmed on-chain, it cannot be undone, reversed, or refunded by Solia or any third party. Transaction fees (gas fees) are determined by the Solana network and are outside of our control.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-zinc-200">7. Intellectual Property</h2>
        <p className="text-sm text-zinc-400 leading-relaxed">
          Users retain rights to AI-generated content they create on the Platform, subject to the terms of the underlying AI model providers. By publishing content on Solia's public feed, you grant the Platform a non-exclusive license to display and distribute that content within the Platform.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-zinc-200">8. Disclaimer of Warranties</h2>
        <p className="text-sm text-zinc-400 leading-relaxed">
          The Platform is provided "as is" and "as available" without warranties of any kind, whether express or implied. Solia does not guarantee uninterrupted access, error-free operation, or the accuracy of AI-generated content. Use the Platform at your own risk.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-zinc-200">9. Limitation of Liability</h2>
        <p className="text-sm text-zinc-400 leading-relaxed">
          To the maximum extent permitted by law, Solia and its team shall not be liable for any direct, indirect, incidental, or consequential damages arising from your use of the Platform, including but not limited to loss of funds, loss of data, or unauthorized access to your wallet.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-zinc-200">10. Modifications</h2>
        <p className="text-sm text-zinc-400 leading-relaxed">
          We reserve the right to modify these Terms of Service at any time. Changes will be effective immediately upon posting. Your continued use of the Platform constitutes acceptance of the updated terms.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-zinc-200">11. Contact</h2>
        <p className="text-sm text-zinc-400 leading-relaxed">
          For questions or concerns regarding these Terms, please contact us via our official channels at{' '}
          <a href="https://solia.live" target="_blank" rel="noopener noreferrer" className="text-indigo-400 hover:text-indigo-300 transition-colors">
            solia.live
          </a>.
        </p>
      </section>
    </div>
  );
};
